"""
generate_plaster_wall_panel.py
==============================
Original half-timber plaster panel wall — NEW geometry (not a retarget
of Wall_Plaster_Straight_Base).

Design (Z-up, metres):
  • Cool slate ashlar plinth with corner quoins
  • Charcoal timber frame: sill, mid-rail, top plate, posts, braces
  • Two bays of recessed limestone plaster (lower + upper)
  • Wood corbels under the top plate + stone coping cap

Module: 2.0 m wide × 0.34 m deep × 3.10 m tall — tiles with the
existing Plaster Wall Straight pieces along +X.

Textures: wall_plaster_panel_textures/ (generated by
generate_plaster_wall_panel_textures.py)

Outputs:
  ~/Desktop/Models/Buildings/WallPlasterPanel.glb
  viewer/public/buildings/WallPlasterPanel.glb

Run:
  python3 generate_plaster_wall_panel_textures.py
  /Applications/Blender.app/Contents/MacOS/Blender --background \\
      --python generate_plaster_wall_panel.py
"""

from __future__ import annotations

import math
import os
import subprocess
import sys

import bpy

ROOT = os.path.dirname(os.path.abspath(__file__))
TEX_DIR = os.path.join(ROOT, "wall_plaster_panel_textures")
SOURCE_DIR = os.path.expanduser("~/Desktop/Models/Buildings")
VIEWER_DIR = os.path.join(ROOT, "viewer/public/buildings")

os.makedirs(SOURCE_DIR, exist_ok=True)
os.makedirs(VIEWER_DIR, exist_ok=True)

# ── Module dimensions ─────────────────────────────────────────────────────

WALL_W = 2.00
WALL_T = 0.28          # plaster / frame thickness
PLINTH_T = 0.34        # plinth slightly deeper
WALL_H = 3.10

PLINTH_H = 0.45
QUOIN_H = 0.70         # corner stones rise above plinth a bit
SILL_H = 0.08
MID_Z = 1.55           # mid-rail centre
PLATE_Z = 2.78         # top plate bottom
POST_W = 0.12
RAIL_H = 0.10
BRACE_T = 0.05
PLASTER_INSET = 0.035  # plaster sits behind timber face
CORBEL_N = 5
COPING_H = 0.12
COPING_OVER = 0.05


def clear_scene() -> None:
    bpy.ops.wm.read_factory_settings(use_empty=True)


def ensure_textures() -> None:
    needed = [
        "Panel_Plaster_BaseColor.png",
        "Panel_Stone_BaseColor.png",
        "Panel_Wood_BaseColor.png",
    ]
    if all(os.path.isfile(os.path.join(TEX_DIR, n)) for n in needed):
        return
    gen = os.path.join(ROOT, "generate_plaster_wall_panel_textures.py")
    print("  generating panel textures…")
    subprocess.check_call(["python3", gen])


def load_image(filename: str) -> bpy.types.Image:
    path = os.path.join(TEX_DIR, filename)
    img = bpy.data.images.load(path, check_existing=True)
    img.pack()
    return img


def make_tex_mat(
    name: str,
    filename: str,
    *,
    roughness: float = 0.85,
    uv_scale: float = 1.0,
) -> bpy.types.Material:
    mat = bpy.data.materials.get(name)
    if mat:
        return mat
    mat = bpy.data.materials.new(name)
    mat.use_nodes = True
    mat.use_backface_culling = False
    nt = mat.node_tree
    nt.nodes.clear()
    out = nt.nodes.new("ShaderNodeOutputMaterial")
    bsdf = nt.nodes.new("ShaderNodeBsdfPrincipled")
    tex = nt.nodes.new("ShaderNodeTexImage")
    tex.image = load_image(filename)
    tex.interpolation = "Linear"
    tc = nt.nodes.new("ShaderNodeTexCoord")
    mp = nt.nodes.new("ShaderNodeMapping")
    mp.inputs["Scale"].default_value = (uv_scale, uv_scale, uv_scale)
    nt.links.new(tc.outputs["UV"], mp.inputs["Vector"])
    nt.links.new(mp.outputs["Vector"], tex.inputs["Vector"])
    nt.links.new(tex.outputs["Color"], bsdf.inputs["Base Color"])
    nt.links.new(bsdf.outputs["BSDF"], out.inputs["Surface"])
    bsdf.inputs["Roughness"].default_value = roughness
    return mat


def mats() -> dict[str, bpy.types.Material]:
    return {
        "plaster": make_tex_mat(
            "panel_plaster", "Panel_Plaster_BaseColor.png", roughness=0.92, uv_scale=1.4,
        ),
        "stone": make_tex_mat(
            "panel_stone", "Panel_Stone_BaseColor.png", roughness=0.90, uv_scale=1.8,
        ),
        "wood": make_tex_mat(
            "panel_wood", "Panel_Wood_BaseColor.png", roughness=0.78, uv_scale=1.2,
        ),
    }


def add_box(
    name: str,
    center: tuple[float, float, float],
    size: tuple[float, float, float],
    mat: bpy.types.Material,
    rotation: tuple[float, float, float] = (0.0, 0.0, 0.0),
) -> bpy.types.Object:
    bpy.ops.mesh.primitive_cube_add(size=1.0, location=center, rotation=rotation)
    obj = bpy.context.active_object
    obj.name = name
    obj.scale = size
    bpy.ops.object.transform_apply(location=False, rotation=True, scale=True)
    obj.data.materials.clear()
    obj.data.materials.append(mat)
    # UVs for textured materials
    bpy.ops.object.mode_set(mode="EDIT")
    bpy.ops.mesh.select_all(action="SELECT")
    bpy.ops.uv.smart_project(angle_limit=66.0, island_margin=0.02)
    bpy.ops.object.mode_set(mode="OBJECT")
    return obj


def join_group(objects: list, name: str) -> bpy.types.Object:
    bpy.ops.object.select_all(action="DESELECT")
    for o in objects:
        o.select_set(True)
    bpy.context.view_layer.objects.active = objects[0]
    if len(objects) > 1:
        bpy.ops.object.join()
    obj = bpy.context.active_object
    obj.name = name
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    return obj


def export_glb(obj: bpy.types.Object, path: str) -> None:
    bpy.ops.object.select_all(action="DESELECT")
    obj.select_set(True)
    bpy.context.view_layer.objects.active = obj
    bpy.ops.export_scene.gltf(
        filepath=path,
        export_format="GLB",
        use_selection=True,
        export_apply=True,
        export_materials="EXPORT",
        export_image_format="AUTO",
        export_texcoords=True,
        export_normals=True,
    )


def build_wall(m: dict[str, bpy.types.Material]) -> list:
    created: list = []
    half_w = WALL_W * 0.5
    y0 = 0.0  # wall centred on Y=0

    # ── 1. Slate plinth ──────────────────────────────────────────────────
    created.append(add_box(
        "plinth",
        center=(0.0, y0, PLINTH_H * 0.5),
        size=(WALL_W + 0.06, PLINTH_T, PLINTH_H),
        mat=m["stone"],
    ))

    # Corner quoins (rise above plinth into the timber zone)
    quoin_w = 0.18
    for side, sign in (("L", -1.0), ("R", +1.0)):
        created.append(add_box(
            f"quoin_{side}",
            center=(sign * (half_w - quoin_w * 0.5 + 0.01), y0, QUOIN_H * 0.5),
            size=(quoin_w, PLINTH_T + 0.02, QUOIN_H),
            mat=m["stone"],
        ))

    # ── 2. Timber frame ──────────────────────────────────────────────────
    timber_y = y0
    timber_depth = WALL_T
    frame_z0 = PLINTH_H  # sill sits on plinth top

    # Sill
    created.append(add_box(
        "sill",
        center=(0.0, timber_y, frame_z0 + SILL_H * 0.5),
        size=(WALL_W - 0.02, timber_depth + 0.02, SILL_H),
        mat=m["wood"],
    ))

    # Top plate
    plate_h = RAIL_H
    created.append(add_box(
        "top_plate",
        center=(0.0, timber_y, PLATE_Z + plate_h * 0.5),
        size=(WALL_W - 0.02, timber_depth + 0.02, plate_h),
        mat=m["wood"],
    ))

    # Mid rail
    created.append(add_box(
        "mid_rail",
        center=(0.0, timber_y, MID_Z),
        size=(WALL_W - 2.0 * POST_W - 0.02, timber_depth, RAIL_H),
        mat=m["wood"],
    ))

    # Posts: left / center / right — full height sill→plate
    post_z0 = frame_z0 + SILL_H
    post_z1 = PLATE_Z
    post_h = post_z1 - post_z0
    post_cz = post_z0 + post_h * 0.5
    post_xs = [-half_w + POST_W * 0.5, 0.0, half_w - POST_W * 0.5]
    for i, px in enumerate(post_xs):
        created.append(add_box(
            f"post_{i}",
            center=(px, timber_y, post_cz),
            size=(POST_W, timber_depth, post_h),
            mat=m["wood"],
        ))

    # Diagonal braces in lower bays (half-timber signature)
    brace_z0 = frame_z0 + SILL_H + 0.04
    brace_z1 = MID_Z - RAIL_H * 0.5 - 0.04
    brace_h = brace_z1 - brace_z0
    brace_cz = (brace_z0 + brace_z1) * 0.5
    bay_half = (WALL_W - 3.0 * POST_W) * 0.25  # approx half bay clear
    # Left bay: brace rising outward; right bay: mirror
    brace_len = math.hypot(bay_half * 1.6, brace_h * 0.85)
    brace_angle = math.atan2(brace_h * 0.85, bay_half * 1.6)
    created.append(add_box(
        "brace_L",
        center=(-half_w * 0.42, timber_y + 0.01, brace_cz),
        size=(BRACE_T, timber_depth * 0.7, brace_len),
        mat=m["wood"],
        rotation=(0.0, brace_angle, 0.0),
    ))
    created.append(add_box(
        "brace_R",
        center=(+half_w * 0.42, timber_y + 0.01, brace_cz),
        size=(BRACE_T, timber_depth * 0.7, brace_len),
        mat=m["wood"],
        rotation=(0.0, -brace_angle, 0.0),
    ))

    # ── 3. Recessed plaster panels (4: lower L/R, upper L/R) ─────────────
    plaster_depth = WALL_T - PLASTER_INSET
    plaster_y = y0 - PLASTER_INSET * 0.5  # slightly recessed toward -Y (outside)

    def panel(name: str, x0: float, x1: float, z0: float, z1: float) -> None:
        cx = 0.5 * (x0 + x1)
        cz = 0.5 * (z0 + z1)
        created.append(add_box(
            name,
            center=(cx, plaster_y, cz),
            size=(x1 - x0, plaster_depth, z1 - z0),
            mat=m["plaster"],
        ))

    gap = 0.015  # clearance from timber
    x_l0 = -half_w + POST_W + gap
    x_l1 = -POST_W * 0.5 - gap
    x_r0 = +POST_W * 0.5 + gap
    x_r1 = +half_w - POST_W - gap

    z_low0 = frame_z0 + SILL_H + gap
    z_low1 = MID_Z - RAIL_H * 0.5 - gap
    z_up0 = MID_Z + RAIL_H * 0.5 + gap
    z_up1 = PLATE_Z - gap

    panel("plaster_low_L", x_l0, x_l1, z_low0, z_low1)
    panel("plaster_low_R", x_r0, x_r1, z_low0, z_low1)
    panel("plaster_up_L", x_l0, x_l1, z_up0, z_up1)
    panel("plaster_up_R", x_r0, x_r1, z_up0, z_up1)

    # ── 4. Corbels under top plate ───────────────────────────────────────
    corbel_z = PLATE_Z - 0.06
    span = WALL_W - 0.24
    for i in range(CORBEL_N):
        t = i / (CORBEL_N - 1) if CORBEL_N > 1 else 0.5
        cx = -span * 0.5 + span * t
        created.append(add_box(
            f"corbel_{i}",
            center=(cx, -WALL_T * 0.35, corbel_z),
            size=(0.08, 0.10, 0.10),
            mat=m["wood"],
        ))

    # ── 5. Stone coping cap ──────────────────────────────────────────────
    coping_z = PLATE_Z + plate_h
    created.append(add_box(
        "coping",
        center=(0.0, y0, coping_z + COPING_H * 0.5),
        size=(WALL_W + COPING_OVER * 2.0, PLINTH_T + COPING_OVER, COPING_H),
        mat=m["stone"],
    ))

    return created


def main() -> None:
    print("\n=== Wall Plaster Panel (original design) ===")
    ensure_textures()
    clear_scene()
    m = mats()
    parts = build_wall(m)
    print(f"  parts: {len(parts)}")
    wall = join_group(parts, "WallPlasterPanel")

    # Report bounds
    xs = [wall.matrix_world @ v.co for v in wall.data.vertices]
    minx = min(v.x for v in xs); maxx = max(v.x for v in xs)
    miny = min(v.y for v in xs); maxy = max(v.y for v in xs)
    minz = min(v.z for v in xs); maxz = max(v.z for v in xs)
    print(
        f"  bounds X[{minx:.3f},{maxx:.3f}] "
        f"Y[{miny:.3f},{maxy:.3f}] Z[{minz:.3f},{maxz:.3f}]"
    )
    print(f"  tris≈{len(wall.data.polygons) * 2}  mats={[s.name for s in wall.material_slots]}")

    for out_dir in (SOURCE_DIR, VIEWER_DIR):
        out_path = os.path.join(out_dir, "WallPlasterPanel.glb")
        export_glb(wall, out_path)
        print(f"  -> {out_path} ({os.path.getsize(out_path) / 1024:.1f} KB)")

    print("DONE")


if __name__ == "__main__":
    main()
